apiVersion: v1
kind: ConfigMap
metadata:
  name: application-properties-product-service
  namespace: prog3360-assignment3
data:
  UNLEASH_API_URL: http://unleash-server:4242/api
  UNLEASH_API_TOKEN: default:development.unleash-insecure-api-token
  UNLEASH_APP_NAME: product-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-properties-order-service
  namespace: prog3360-assignment3
data:
  SERVER_PRODUCT_URL: http://product-service:8081
  UNLEASH_API_URL: http://unleash-server:4242/api
  UNLEASH_API_TOKEN: default:development.unleash-insecure-api-token
  UNLEASH_APP_NAME: order-service
