# ConfigMap - application config
# Shared environment variables for both services (injected via envFrom)
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: prog3360-dinh-seo
data:
  # application environment name (A3 Instruction)
  APP_ENV: "production"
  # downstream service URL (A3 Instruction): only 'order-service' uses this to reach 'product-service'
  SERVER_PRODUCT_URL: "http://product-service:8081"
  # version label (A3 Instruction)
  APP_VERSION: "v1-blue"
  
  # Assignment 4 - Part 3: Zipkin endpoint for tracing (K8s DNS)
  # In docker-compose/local: falls back to localhost:9411 via application.properties default
  # In K8s: this env var overrides the default so spans are sent to the Zipkin pod
  MANAGEMENT_TRACING_EXPORT_ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
