apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: prog3360-assignment3
spec:
  selector:
    app: order-service
    version: blue
  ports:
    - port: 8082
      targetPort: 8082
